name: boarding
version: 0.0.1
description: A package for board games or canvas drawings. The package has both model and view libraries. See the example folder to see how to use the boarding package.
homepage: https://github.com/ednet-dev/cms

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=3.3.10"

documentation: http://goo.gl/kXlDOJ

dependencies:
  ednet_core:
    path: ../../../ednet_cms/packages/ednet_core
dev_dependencies:
  test:
